### ISSUE TITLE
Register User

### ISSUE THREAD

**Issue by UniqueDevs154** [UniqueDevs154/Nessa-E-Commerce#1]
**As a user, I want to register an account so that I can make purchases.**

**Checklist**:
**Frontend**:
- [ ] Create registration form (#1001)
- [ ] Validate user input on the client side (#1002)
- [ ] Connect to the API endpoint for registration (#1003)

**Backend**:
- [ ] Create API endpoint for user registration (#1004)
- [ ] Validate user input on the server side (#1005)
- [ ] Save user data to the database (#1006)
- [ ] Send confirmation email (#1007)

**Labels**:
- Epic: User Management
- Size: 3 points
- Priority: High
