### ISSUE TITLE
Confirm Order

### ISSUE THREAD

**Issue by UniqueDevs154** [UniqueDevs154/Nessa-E-Commerce#10]
**As a customer, I want to receive an order confirmation so that I know my purchase was successful.**

**Checklist**:
**Frontend**:
- [ ] Create order confirmation page (#1010)
- [ ] Display order details to the user (#1011)

**Backend**:
- [ ] Send confirmation email to user (#1012)
- [ ] Update order status in the database (#1013)

**Labels**:
- Epic: Order Management
- Size: 3 points
- Priority: High
