### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by UniqueDevs154** [UniqueDevs154/Nessa-E-Commerce#12]
**As a user, I want to recover my password if I forget it.**

**Checklist**:
**Frontend**:
- [ ] Create password recovery form (#1211)
- [ ] Allow user to reset password (#1212)

**Backend**:
- [ ] Send recovery email (#1213)
- [ ] Verify recovery link (#1214)

**Labels**:
- Epic: User Management
- Size: 3 points
- Priority: Medium
