### ISSUE TITLE
Log In User

### ISSUE THREAD

**Issue by UniqueDevs154** [UniqueDevs154/Nessa-E-Commerce#2]
**As a user, I want to log in to my account so that I can access my profile and orders.**

**Checklist**:
**Frontend**:
- [ ] Create login form (#2001)
- [ ] Validate user credentials on the client side (#2002)
- [ ] Connect to the API endpoint for login (#2003)

**Backend**:
- [ ] Create API endpoint for user login (#2004)
- [ ] Authenticate user credentials (#2005)
- [ ] Handle session management (#2006)

**Labels**:
- Epic: User Management
- Size: 3 points
- Priority: High
