### ISSUE TITLE
Log Out User

### ISSUE THREAD

**Issue by UniqueDevs154** [UniqueDevs154/Nessa-E-Commerce#3]
**As a user, I want to log out of my account to secure my information.**

**Checklist**:
**Frontend**:
- [ ] Implement logout functionality (#3001)
- [ ] Redirect to homepage (#3002)

**Backend**:
- [ ] Invalidate user session (#3003)

**Labels**:
- Epic: User Management
- Size: 1 point
- Priority: Medium
