### ISSUE TITLE
Add to Cart

### ISSUE THREAD

**Issue by UniqueDevs154** [UniqueDevs154/Nessa-E-Commerce#6]
**As a customer, I want to add products to my cart so that I can purchase multiple items at once.**

**Checklist**:
**Frontend**:
- [ ] Create "Add to Cart" button (#6001)
- [ ] Update cart session data on the client side (#6002)
- [ ] Display cart summary (#6003)

**Backend**:
- [ ] Create API endpoint to manage cart items (#6004)
- [ ] Update cart session data on the server side (#6005)

**Labels**:
- Epic: Cart Management
- Size: 2 points
- Priority: High
