### ISSUE TITLE
View Cart

### ISSUE THREAD

**Issue by UniqueDevs154** [UniqueDevs154/Nessa-E-Commerce#7]
**As a customer, I want to view my cart to review my selected items before checkout.**

**Checklist**:
**Frontend**:
- [ ] Create cart page (#7001)
- [ ] Display items in the cart (#7002)
- [ ] Calculate total price (#7003)

**Backend**:
- [ ] Create API endpoint to fetch cart details (#7004)

**Labels**:
- Epic: Cart Management
- Size: 2 points
- Priority: High
