### ISSUE TITLE
Proceed to Checkout

### ISSUE THREAD

**Issue by UniqueDevs154** [UniqueDevs154/Nessa-E-Commerce#8]
**As a customer, I want to proceed to checkout to finalize my purchase.**

**Checklist**:
**Frontend**:
- [ ] Create checkout button (#8001)
- [ ] Redirect to checkout page (#8002)

**Backend**:
- [ ] No specific backend tasks (#8003)

**Labels**:
- Epic: Checkout
- Size: 3 points
- Priority: High
